Added NaNReporter and HighMaReporter to LettuceCFD
lettucecfd/lettuce pull request #248
Opened 2024-09-02 11:40 UTC by MaxBille

## Description

Closes #174 
Closes #272 
Adding two reporters, that check for signs of simulation crashes (NaN in f or Ma > 0.3 in u) and abort simulation with respective abort messages, optional final vtk-frame and (in case of HighMaReporter) optional output file with locations of the 100 highest velocity magnitudes for crash-troubleshooting and analysis.

NaNReporter:
- checks f in interval steps for any NaN value. If NaN is found, simulation is aborted.
- if outdir is provided, lists indices q,x,y,[z] for all found NaN values (attention: produces large files for large intervals, because NaN replicates through the domain fast.
- "old" argument (True, False) is for backwards compatibility with lettuce that has no aborting functionality in the simulation.py class. No vtk output in this case...
- vtk argument (True, False) allows for vtk output of the current single flow state frame to outdir (if vtk_dir is not specified) or vtk_dir (if specified)

HighMaReporter:
- calculates mach number from norm(u(f)) every interval steps and checks if Ma > 0.3 occurs. If Ma > 0.3 is found, simulation is aborted. The location (in LU coordinates) of up to 100 highest Ma numbers in the domain are reported to a file in outdir, if outdir argument is provided.
- "old" argument (True, False) is for backwards compatibility with lettuce that has no aborting functionality in the simulation.py class. No vtk output in this case...
- vtk argument (True, False) allows for vtk output of the current single flow state frame to outdir (if vtk_dir is not specified) or vtk_dir (if specified)
- relies on unravel_index() method for torch.tensors, defined in the same file, for sorting and selection of high-Ma-locations.

DISCLAIMER: originally written for a modified version of lettuceCFD, based on Version 0.2.3; Adaptation for new Lettuce Master pending...

## Checklist

 - [x] This pull request is associated to an issue
 - [x] This PR contains a description
 - [x] Add someone else as reviewer and wait for approval before merging.

2024-09-02 11:40 UTC, pep8speaks commented
Hello @MaxBille! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`lettuce/ext/_reporter/__init__.py`](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/__init__.py):

> [Line 5:27](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/__init__.py#L5): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`lettuce/ext/_reporter/nan_repoter.py`](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py):

> [Line 13:1](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L13): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 15:80](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L15): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (151 > 79 characters)
> [Line 16:80](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L16): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (149 > 79 characters)
> [Line 18:80](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L18): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (137 > 79 characters)
> [Line 36:9](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L36): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 37:9](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L37): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 38:9](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L38): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 62:25](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L62): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 65:80](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L65): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)
> [Line 66:80](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L66): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (116 > 79 characters)
> [Line 69:80](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L69): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 79 characters)
> [Line 70:80](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L70): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (178 > 79 characters)
> [Line 71:80](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L71): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (135 > 79 characters)
> [Line 72:80](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L72): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (175 > 79 characters)
> [Line 74:80](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L74): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 77:80](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L77): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 78:80](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L78): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)
> [Line 80:80](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L80): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 82:80](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L82): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (103 > 79 characters)
> [Line 84:80](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L84): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 86:80](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L86): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 79 characters)
> [Line 90:80](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L90): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 117:80](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L117): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (137 > 79 characters)
> [Line 167:80](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L167): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 172:80](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L172): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (150 > 79 characters)
> [Line 173:21](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L173): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 173:80](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L173): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (135 > 79 characters)
> [Line 177:80](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L177): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (112 > 79 characters)
> [Line 180:26](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L180): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 185:80](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L185): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (95 > 79 characters)
> [Line 187:80](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L187): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 188:80](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext/_reporter/nan_repoter.py#L188): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (115 > 79 characters)
> [Line 190:80](https://github.com/lettucecfd/lettuce/blob/8757a090f9b383f09c6e8b7a7b2c973c1261acf6/lettuce/ext [...]

2024-10-16 11:16 UTC, McBs commented on examples/advanced_flows/FailingTGVandObstacle.py
> +simulation = lt.BreakableSimulation(
Do the reporters only work with this specific `Simulation` class (i.e. `BreakableSimulation`)?
If not, I prefer to initialize this class within the example script (i.e. header).

2025-08-06 13:46 UTC, McBs commented on examples/advanced_flows/FailingTGVandObstacle.py
> +simulation = lt.BreakableSimulation(
Hi @MaxBille 
Is there an update on this?

2025-09-04 16:08 UTC, PhiSpel requested changes
1. Could you check if we need to set non_native in BreakableSimulation? If so, can you rename to `BreakableSimulationNonNative`?
2. Maybe rename example to `FailingTGVandObstacle.py`?

2025-12-15 11:15 UTC, MaxBille commented
@PhiSpel would you mind, reviewing the changes I've made, regarding your change requests and recommendation? :) (if you have the time...)

2025-12-15 11:35 UTC, PhiSpel commented on lettuce/ext/_reporter/nan_repoter.py
> +def unravel_index(indices: torch.Tensor, shape: tuple[int, ...],
Why do we need this here? Is this not included in torch? https://docs.pytorch.org/docs/stable/generated/torch.unravel_index.html

2025-12-15 11:37 UTC, PhiSpel commented on lettuce/ext/_reporter/nan_repoter.py
> +    def first_100(self, simulation: 'Simulation'):
Is this ever applied?

2025-12-15 11:37 UTC, PhiSpel commented on lettuce/ext/_reporter/vtk_reporter.py
> +__all__ = ['VTKReporter', 'write_vtk']
Should we make this a public function? Why not keep it guarded behind `VTKReporter`?

2025-12-15 13:14 UTC, MaxBille commented on lettuce/ext/_reporter/nan_repoter.py
> +def unravel_index(indices: torch.Tensor, shape: tuple[int, ...],
at the time of writing the functionality of the torch- and numpy-version of unravel_index worked differently and the torch-version did not work for this application. I'll have to check, if this is still a thing in current torch implementations

UPDATE: I have updated the code to use the native torch.unravel_index() method!

2025-12-15 13:19 UTC, MaxBille commented on lettuce/ext/_reporter/vtk_reporter.py
> +__all__ = ['VTKReporter', 'write_vtk']
Update: it now has to be public, because the nan- and high-ma reporter use the write_vtk() method to write a vtk without the need to initialize and call a vtk-reporter!

2025-12-17 19:49 UTC, PhiSpel commented on examples/advanced_flows/FailingTGVandObstacle.py
> +# b) unstable obstacle flow,m that causes high Ma values (Ma > 0.3), which are
typo

2025-12-17 19:50 UTC, PhiSpel commented on lettuce/ext/_reporter/__init__.py
> +#from .nan_repoter import *
remove redundant

2025-12-17 19:50 UTC, PhiSpel commented on lettuce/ext/_reporter/failure_reporter.py
> +# class Reporter: ...
remove (?)

2025-12-17 19:56 UTC, PhiSpel commented on lettuce/ext/_reporter/failure_reporter.py
> +    def is_failed(self, simulation):
This is default, so no need to overwrite.

But I think I see what you did there. I like the idea of abstract superclass. How about making FailureReporterBase an ABC class? (like Flow->ExtFlow->...) Implement like `class FailureReporterBase(Reporter, ABC):` and mark 
```
@abstractmethod
def is_failed(self, simulation: 'Simulation') -> bool:
  ...
```

Same applies to `get_results`. `locations_string` was intentionally not part of `FailureReporterBase`?

2025-12-17 19:57 UTC, PhiSpel commented on lettuce/ext/_reporter/nan_repoter.py
> +    def __call__(self, simulation: 'Simulation'):
Since you import `Simulation` with no apparent issues, you can type it directly. Keep in mind, though: This must be a `BreakableSimulation`

2025-12-17 20:00 UTC, PhiSpel commented on lettuce/ext/_reporter/nan_repoter.py
> +                # TODO: maybe make this more robust with a failed-flag in simulation and not rely on flow.i to be high/low?
Sure! Since we're working with `BreakableSimulation` anyway, it can just get a flag `lastIteration`, such that any other `Reporter` (also `VTKReporter`!) can also check if the simulation failed and output one last time. This is also implemented in NATriuM.

This may have been my own TODO-comment, btw ... :) So, for now, you could just post ths into another issue

2025-12-18 11:01 UTC, MaxBille commented on examples/advanced_flows/FailingTGVandObstacle.py
> +# b) unstable obstacle flow,m that causes high Ma values (Ma > 0.3), which are
corrected

2025-12-18 11:02 UTC, MaxBille commented on lettuce/ext/_reporter/__init__.py
> +#from .nan_repoter import *
removed

2025-12-18 11:04 UTC, MaxBille commented on lettuce/ext/_reporter/failure_reporter.py
> +# class Reporter: ...
removed. Will go over comments etc. again

2025-12-18 11:10 UTC, MaxBille commented on lettuce/ext/_reporter/failure_reporter.py
> +    def is_failed(self, simulation):
ABC: good idea! will do
location_string: the NaN reporter reports qxy(z) dimensions, the HighMa reporter reports online xy(z) dimensions, so they need separate location strings. But I'll make it an abstractmethod too.

2025-12-18 11:19 UTC, MaxBille commented on lettuce/ext/_reporter/nan_repoter.py
> +    def __call__(self, simulation: 'Simulation'):
removed Simulation. Made Typing check for BreakableSimulation

2025-12-18 11:24 UTC, MaxBille commented on lettuce/ext/_reporter/nan_repoter.py
> +                # TODO: maybe make this more robust with a failed-flag in simulation and not rely on flow.i to be high/low?
will do

2025-12-18 13:03 UTC, PhiSpel commented on examples/advanced_flows/FailingTGVandObstacle.py
> +simulation = lt.BreakableSimulation(
@McBs yes, it should be BreakableSimulation since we manipulate `simulation.flow.i`. If `simulation` this is not `BreakableSimulation`, it will continue running because `call()` contains a blind for-loop (https://github.com/lettucecfd/lettuce/blob/d04e15646103e3aeb54a6fe7799b5c98435c8543/lettuce/_simulation.py#L243) that won't be broken.

2025-12-18 13:04 UTC, PhiSpel commented on lettuce/ext/_reporter/nan_repoter.py
> +    def __call__(self, simulation: 'Simulation'):
@MaxBille have you tried this?

2025-12-18 13:05 UTC, PhiSpel commented on lettuce/ext/_reporter/nan_repoter.py
> +                # TODO: maybe make this more robust with a failed-flag in simulation and not rely on flow.i to be high/low?
@MaxBille is this a won't-do, or something for a new issue?

2026-03-16 13:45 UTC, merged